# Generated by Django 2.2.1 on 2020-02-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obs_Prop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_title', models.CharField(max_length=200)),
                ('obs_type', models.CharField(max_length=200)),
                ('field_type', models.CharField(max_length=200)),
                ('coords_ra', models.FloatField()),
                ('coords_dec', models.FloatField()),
                ('fov', models.FloatField()),
                ('magnitude', models.FloatField()),
                ('desired_exposure', models.FloatField()),
                ('description', models.CharField(max_length=2000)),
                ('settings', models.CharField(max_length=2000)),
                ('user_id', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
