# Generated by Django 2.2.1 on 2020-02-18 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_propose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obs_prop',
            name='submitted_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
