# Generated by Django 2.2.1 on 2020-02-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_propose', '0005_auto_20200221_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='obs_prop',
            name='accepted_users',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obs_prop',
            name='requested_users',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
