# Generated by Django 2.2.1 on 2020-02-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_propose', '0006_auto_20200221_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='obs_prop',
            name='completed_users',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
