# Generated by Django 2.2.1 on 2020-02-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_propose', '0009_auto_20200226_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obs_prop',
            old_name='desired_exposure',
            new_name='exp_max',
        ),
        migrations.AddField(
            model_name='obs_prop',
            name='exp_min',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
