# Generated by Django 2.2.1 on 2020-02-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_propose', '0010_auto_20200226_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='obs_prop',
            name='exps',
            field=models.CharField(default='', max_length=20000),
            preserve_default=False,
        ),
    ]
