# Generated by Django 2.2 on 2020-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_propose', '0012_auto_20200310_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='obs_prop',
            name='rejected_users',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
