# Generated by Django 2.2 on 2020-06-25 16:52

from django.db import migrations
import likert_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obs_rev',
            name='accuracy',
            field=likert_field.models.LikertField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obs_rev',
            name='data_quality',
            field=likert_field.models.LikertField(blank=True, null=True),
        ),
    ]
