# Generated by Django 2.2 on 2020-06-27 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('obs_review', '0005_auto_20200627_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='obs_rev',
            name='reviewed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
