# Generated by Django 2.2 on 2020-06-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_review', '0007_auto_20200627_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='obs_rev',
            name='title',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
