# Generated by Django 2.2.1 on 2020-03-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_id', models.CharField(max_length=200)),
                ('obs_id', models.IntegerField()),
                ('ama_id', models.CharField(max_length=300)),
                ('lights_names', models.CharField(max_length=20000)),
                ('darks_names', models.CharField(max_length=20000)),
                ('flats_names', models.CharField(max_length=20000)),
                ('bias_names', models.CharField(max_length=20000)),
                ('obs_comments', models.CharField(max_length=20000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='data_files/')),
            ],
        ),
    ]
