# Generated by Django 2.2.1 on 2020-03-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ama_obs_overview', '0002_auto_20200302_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_details',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file_details',
            name='sorted',
            field=models.BooleanField(default=False),
        ),
    ]
