# Generated by Django 2.2.1 on 2020-02-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proOB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=200)),
                ('field_of_interest', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
            ],
        ),
    ]
