# Generated by Django 2.2 on 2020-06-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='obs_rev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_title', models.CharField(max_length=200)),
                ('prop_title', models.CharField(max_length=200)),
                ('data_quality', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('review', models.CharField(max_length=2000)),
            ],
        ),
    ]
