# Generated by Django 2.2 on 2020-06-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_review', '0003_auto_20200625_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='obs_rev',
            name='obs_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obs_rev',
            name='prop_pk',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
