# Generated by Django 2.2 on 2020-06-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obs_review', '0006_obs_rev_reviewed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obs_rev',
            old_name='reviewed_at',
            new_name='posted_at',
        ),
    ]
