# Generated by Django 2.2.1 on 2020-02-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmaOB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('avail', models.BooleanField()),
                ('telescope_aper', models.FloatField()),
                ('telescope_flength', models.FloatField()),
                ('det_mod', models.CharField(max_length=200)),
                ('det_pix_scale', models.FloatField()),
                ('detector_dimensions', models.CharField(max_length=200)),
            ],
        ),
    ]
