# Generated by Django 2.2.1 on 2020-02-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amateurOnboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amaob',
            name='user_id',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
