# Generated by Django 2.2.1 on 2020-02-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amateurOnboarding', '0003_amaob_fov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amaob',
            name='fov',
        ),
        migrations.RemoveField(
            model_name='amaob',
            name='user_id',
        ),
    ]
