# Generated by Django 2.2.1 on 2020-02-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amateurOnboarding', '0004_auto_20200207_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='amaob',
            name='fov',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amaob',
            name='user_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
