# Generated by Django 2.2.1 on 2020-02-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amateurOnboarding', '0007_amaob_obs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='amaob',
            name='credits',
            field=models.CharField(default='', max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amaob',
            name='total_credits',
            field=models.FloatField(default=0.0),
        ),
    ]
