# Generated by Django 2.2.1 on 2020-03-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amateurOnboarding', '0015_amaob_qe'),
    ]

    operations = [
        migrations.AddField(
            model_name='amaob',
            name='SQM',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
