# Generated by Django 2.2.1 on 2020-02-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_propose', '0002_obs_prop_submitted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='obs_prop',
            name='selected_users',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
