# Generated by Django 2.2.1 on 2020-02-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_propose', '0003_obs_prop_selected_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='obs_prop',
            name='unselected_users',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
