# Generated by Django 2.2.1 on 2020-02-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_propose', '0004_obs_prop_unselected_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obs_prop',
            name='coords_dec',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='obs_prop',
            name='coords_ra',
            field=models.CharField(max_length=200),
        ),
    ]
