# Generated by Django 2.2.1 on 2020-02-25 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_propose', '0007_obs_prop_completed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='obs_prop',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obs_prop',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
