# Generated by Django 2.2.1 on 2020-02-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_propose', '0008_auto_20200225_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obs_prop',
            name='end_date',
        ),
        migrations.AddField(
            model_name='obs_prop',
            name='no_of_nights',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
