# Generated by Django 2.2.1 on 2020-03-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_propose', '0011_obs_prop_exps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obs_prop',
            old_name='fov',
            new_name='max_fov',
        ),
        migrations.AddField(
            model_name='obs_prop',
            name='min_fov',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
