# Generated by Django 2.2.1 on 2020-02-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amateurOnboarding', '0002_amaob_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='amaob',
            name='fov',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
