# Generated by Django 2.2.1 on 2020-02-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amateurOnboarding', '0008_auto_20200225_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='amaob',
            name='Booked_dates',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amaob',
            name='read_noise',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
