# Generated by Django 2.2.1 on 2020-02-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amateurOnboarding', '0009_auto_20200226_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amaob',
            old_name='Booked_dates',
            new_name='booked_dates',
        ),
    ]
