# Generated by Django 2.2.1 on 2020-03-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amateurOnboarding', '0010_auto_20200226_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amaob',
            name='avail',
        ),
        migrations.AddField(
            model_name='amaob',
            name='obs_img',
            field=models.ImageField(default='', upload_to='obs_images'),
            preserve_default=False,
        ),
    ]
