# Generated by Django 2.2.1 on 2020-03-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amateurOnboarding', '0011_auto_20200303_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='amaob',
            name='chip_name',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='amaob',
            name='telescope_mod',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amaob',
            name='det_mod',
            field=models.CharField(max_length=2000),
        ),
    ]
