# Generated by Django 2.2.1 on 2020-03-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amateurOnboarding', '0013_auto_20200304_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amaob',
            name='read_noise',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
